spring.output.ansi.enabled: ALWAYS

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  application:
    name: news-company-bankruptcy

# Put your keys or use VM(or JVM) Option.
telegram-api:
  host: # Put your host with token.
  chat-id: # Put you chat-id.

naver-news:
  host: https://search.naver.com